# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker

# event trigger
# main 브랜치에 push가 되었을 때 실행
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: npm_install
      working-directory: ../nodejs/todo-app
      run: npm install
        
    - name: run_test_code
      working-directory: ../nodejs/todo-app
      run: npm test

    -
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: teichae/node
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./nodejs/todo-app/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:1.0
        # tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

    # - name: Build docker image
    #   run: |
    #   cd 
    #   docker build . -t todo-app